version: '3'
services:
  reposado:
    image: "macadmins/reposado"
    ports:
      - "443:443"
    volumes:
      - reposado:/reposado

  margarita:
    image: "margarita"
    ports:
     - "80:80"
    volumes:
      - reposado:/reposado
    depends_on:
      - reposado

volumes:
  reposado:
